# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=145)),
                ('tweet_profile_picture', models.CharField(max_length=2084)),
                ('tweet_expand_url', models.CharField(max_length=2084)),
                ('tweet_image', models.CharField(max_length=2084)),
            ],
        ),
    ]
