# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='id',
        ),
        migrations.AddField(
            model_name='tweets',
            name='tweet_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
