# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0002_auto_20170123_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tweets',
            new_name='tweet',
        ),
    ]
