# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0003_auto_20170123_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_Name', models.CharField(max_length=100)),
                ('account_handle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('hashtag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hashtag_hash', models.CharField(max_length=100)),
            ],
        ),
    ]
