# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0004_account_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_expand_url',
            field=models.CharField(blank=True, max_length=2084),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_image',
            field=models.CharField(blank=True, max_length=2084),
        ),
    ]
