# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0005_auto_20170201_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_id',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
