# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0006_auto_20170201_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag_hash',
            new_name='hashtag',
        ),
    ]
